### ISSUE TITLE
Broken with Rails 5.1.5

### ISSUE THREAD

**Issue by pzac** [ifad/chronomodel#69]
`ArgumentError:
        #<struct ChronoModel::Patches::Preloader::AS_OF_PRELOAD_SCOPE as_of_time=2018-03-19 15:26:24 UTC, values={}, where_clause=#<ActiveRecord::Relation::WhereClause:0x007f87224a8f20 @predicates=[], @binds=[], @referenced_columns=#<Set: {}>>, joins_values=[]> is not an ActiveRecord::Relation`

**Comment by vjt** [comment]
Fixed in [v0.12.2](https://github.com/ifad/chronomodel/releases/tag/v0.12.2).

Explanation of the fix in 21863cb. Full set of changes including further refactoring [here](https://github.com/ifad/chronomodel/compare/3c585c1%5E%5E...3c585c1).

Released to RubyGems as [v0.12.2](https://rubygems.org/gems/chrono_model/versions/0.12.2).
